name: kan
dependencies:
  - python=3.9.7
  - pip
  - ipykernel
  - pip:
    - matplotlib==3.6.2
    - numpy==1.24.4
    - scikit_learn==1.1.3
    - setuptools==65.5.0
    - sympy==1.11.1
    - torch==2.2.2
    - tqdm==4.66.2
    - git+https://github.com/KindXiaoming/pykan.git
    - mplhep
    - tensorflow[and-cuda]
    - pandas
    - moviepy
    - librosa==0.6.0
    - pyyaml
